# PostgreSQL
postgres:
    image: postgres:9.6.0
    ports:
      - 5432:5432 # Bind host port 5432 to PostgreSQL port 5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    env_file: .env
    environment:
      - LC_ALL=C.UTF-8

# Django app
app:
    build: .
#    command: dev
    command: uwsgi
    ports:
      - 8000:8000
      - 8001:8001
    volumes:
      - ./app:/usr/src/app
   # links:
    #  - postgres:postgres
    env_file: .env
    environment:
      - DEBUG=True
      - PORT=8000
      - SECRET_KEY=JeffreyLebowski
      - WSGI_MODULE=freelancers.wsgi:application

web:
    build: nginx
    ports:
      - 80:80
    links:
      - app:app
