# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-28 14:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('freelancers', '0003_auto_20170428_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='experiences',
            field=models.ManyToManyField(to='freelancers.Experience'),
        ),
    ]
