# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-28 15:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('freelancers', '0005_auto_20170428_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='type_of_contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freelancers.TypeOfContract'),
        ),
    ]
