# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-02 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancers', '0006_auto_20170428_1527'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='owner_id',
            new_name='company_id',
        ),
        migrations.AddField(
            model_name='project',
            name='freelancers',
            field=models.ManyToManyField(to='freelancers.Profile'),
        ),
    ]
