# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-02 17:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelancers', '0009_auto_20170502_1653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='company_id',
            new_name='user',
        ),
    ]
