# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-02 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancers', '0010_auto_20170502_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='user',
        ),
        migrations.AlterField(
            model_name='profile',
            name='experiences',
            field=models.ManyToManyField(to='freelancers.Experience'),
        ),
    ]
