# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-07 19:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelancers', '0015_project_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='company',
        ),
    ]
