# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-08 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancers', '0020_auto_20170507_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='freelancers',
            field=models.ManyToManyField(null=True, to='freelancers.Profile'),
        ),
    ]
