# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-11 15:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('freelancers', '0021_auto_20170508_1042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='user',
        ),
        migrations.AddField(
            model_name='company',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='social_accounts',
            field=models.ManyToManyField(to='freelancers.SocialAccounts'),
        ),
        migrations.AddField(
            model_name='company',
            name='web_page',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='freelancers.Company'),
        ),
        migrations.AlterField(
            model_name='project',
            name='freelancers',
            field=models.ManyToManyField(to='freelancers.Profile'),
        ),
    ]
