# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-29 20:55
from __future__ import unicode_literals

from django.db import migrations, models
import freelancers.models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancers', '0024_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(null=True, upload_to=freelancers.models.set_upload_to),
        ),
    ]
