# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-31 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancers', '0025_auto_20170529_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
