# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-05 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancers', '0026_auto_20170531_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.CharField(blank=True, default='https://secure.gravatar.com/avatar/hash.jpg?size=150', max_length=200, null=True),
        ),
    ]
