# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-05 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancers', '0027_auto_20170605_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('type',),
            },
        ),
    ]
