# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-05 17:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelancers', '0028_profiletype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileType',
        ),
    ]
