# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-05 17:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('freelancers', '0030_profiletype'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='freelancers.ProfileType'),
            preserve_default=False,
        ),
    ]
