# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-07 00:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancers', '0031_profile_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=200)),
                ('date', models.DateField()),
            ],
            options={
                'ordering': ('university',),
            },
        ),
    ]
