# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-07 01:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancers', '0032_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='education',
            field=models.ManyToManyField(to='freelancers.Education'),
        ),
    ]
