# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-07 15:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('freelancers', '0034_auto_20170607_1032'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_address', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='company',
            name='social_accounts',
        ),
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.CharField(blank=True, default='https://secure.gravatar.com/avatar/hash.jpg?size=150', max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='SocialAccounts',
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freelancers.SocialNetwork'),
        ),
        migrations.AddField(
            model_name='company',
            name='social_account',
            field=models.ManyToManyField(to='freelancers.SocialAccount'),
        ),
    ]
