# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-12 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancers', '0040_auto_20170712_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='date_generated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
