# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-12 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancers', '0043_auto_20170712_1144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='price',
            new_name='unit_price',
        ),
        migrations.RenameField(
            model_name='contract',
            old_name='type_of_contract',
            new_name='unit_type',
        ),
        migrations.AddField(
            model_name='contract',
            name='currency',
            field=models.CharField(choices=[('EUR', 'Euro'), ('USD', 'Dollar')], default='EUR', max_length=3),
        ),
    ]
