# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-13 08:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('freelancers', '0044_auto_20170712_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='type_of_contract',
        ),
        migrations.RemoveField(
            model_name='socialaccount',
            name='profile',
        ),
        migrations.AddField(
            model_name='expendedtime',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expense',
            name='currency',
            field=models.CharField(choices=[('EUR', 'Euro'), ('USD', 'Dollar')], default='EUR', max_length=3),
        ),
        migrations.AddField(
            model_name='expense',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='description',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='expendedtime',
            name='notes',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='expendedtime',
            name='start_time',
            field=models.DateTimeField(help_text='Start time of the task.', null=True),
        ),
        migrations.AlterField(
            model_name='expendedtime',
            name='stop_time',
            field=models.DateTimeField(help_text="Stop time of the task. This time needs to be of a higher date then start_time. Setting this fieldmeans the amount of time spent on the task will be added to the current 'time'.", null=True),
        ),
        migrations.AlterField(
            model_name='expendedtime',
            name='time',
            field=models.IntegerField(default=0, help_text='Time spent on the task in seconds. Time registered through start and stop time will be automatically added to this field'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='notes',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='kindoftask',
            name='description',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profiletype',
            name='description',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='skill',
            name='description',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='web_address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='typeofcontract',
            name='description',
            field=models.TextField(max_length=200),
        ),
    ]
