# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-13 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancers', '0045_auto_20170713_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expendedtime',
            name='stop_time',
            field=models.DateTimeField(help_text="Stop time of the task. This time needs to be of a higher date then start_time. Setting this field means the amount of time spent on the task will be added to the current 'time'.", null=True),
        ),
    ]
