# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-18 16:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelancers', '0046_auto_20170713_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expendedtime',
            name='kind_of_task',
        ),
    ]
