# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-18 16:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('freelancers', '0047_remove_expendedtime_kind_of_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='expendedtime',
            name='kind_of_task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='freelancers.KindOfTask'),
            preserve_default=False,
        ),
    ]
