# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-20 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancers', '0048_expendedtime_kind_of_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='pdf',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
