# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-25 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancers', '0049_invoice_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='pdf',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
