# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-03 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancers', '0050_auto_20170725_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='profile',
        ),
        migrations.AddField(
            model_name='education',
            name='profile',
            field=models.ManyToManyField(to='freelancers.Profile'),
        ),
        migrations.RemoveField(
            model_name='experience',
            name='profile',
        ),
        migrations.AddField(
            model_name='experience',
            name='profile',
            field=models.ManyToManyField(to='freelancers.Profile'),
        ),
    ]
