# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-03 20:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelancers', '0052_auto_20170803_2048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='user',
            new_name='profile',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='user',
            new_name='profile',
        ),
    ]
