# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-17 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='achievement',
            field=models.TextField(max_length=511, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='reason',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='story',
            field=models.TextField(max_length=511, null=True),
        ),
    ]
